### ISSUE TITLE
CV edit don't work on brave browser

### ISSUE THREAD

**Issue by Alecell** [Cv-Keep/cvkeep-frontend#21]
On brave browser, when I create my account I see this:
![image](https://user-images.githubusercontent.com/13935760/138009507-a5dd6019-e000-4e95-8343-453fe240dac9.png)

When I tried the same account on Firefox works as expected:
![image](https://user-images.githubusercontent.com/13935760/138009562-a6a53fb0-1994-477a-a165-94c25d17a911.png)

**Comment by felippe-regazio** [comment]
[DUPLICATED]

This is because of this issue: https://github.com/Cv-Keep/cvkeep-frontend/issues/6

It was already reported. Some browsers are adding thirdy-party cookies policy.
Since the CV API is in another domain and decoupled from the front, the browser see the thirdy party login cookie and blocks it.
Try to enable thirdy party cookies for this address and the login will work.
We are already working to solve the issue.

**Comment by felippe-regazio** [comment]
Done & Deployed: https://github.com/Cv-Keep/cvkeep-frontend/issues/6
